puppetlabs/puppetlabs-catalog_preview

lib/puppet/application/preview.rb

Puppet versions < 4.0 will make an attempt to change the user and group
of a log destination file to 'puppet'. This fails unless the user has
root privileges. This commit changes the catalog_preview command so that
it detects when the process owner is non-root user and then sets the
`Puppet[:user]` and `Puppet[:group]` to values that correspond to the
`uid` and `gid` of the process owner, thus preventing permission errors
further on.

(PRE-72) Use process owner as default for Puppet user and group

---

lib/puppet/application/preview.rb
lib/puppet/indirector/catalog/diff_compiler.rb
lib/puppet_x/puppetlabs/preview/api/documentation/preview-help.md
spec/fixtures/etc/puppet/environments/env4x/environment.conf
spec/fixtures/etc/puppet/environments/env4x/manifests/site.pp
spec/fixtures/etc/puppet/environments/production/manifests/site.pp
spec/fixtures/etc/puppet/puppet.conf
spec/integration/preview_spec.rb
spec/unit/preview_spec.rb

This PR makes it is possible to generate this diff by compiling the same environment twice, switching the parser from 'current' to 'future' between the compiles. It also improves how unit tests interface with the application, fixes some style related issues, and some minor bugs.

(PRE-66) Make it possible to produce diff using only one environment

---

lib/puppet/application/preview.rb
lib/puppet_x/puppetlabs/migration/catalog_delta_model.rb
lib/puppet_x/puppetlabs/preview/api/documentation/preview-help.md
spec/integration/preview_spec.rb

All CLI options in the Puppet code-base uses dash as word separator.
Before this commit, catalog-preview used an underscore. This commit
changes this so that both dash and underscore can be used (to retain
backward compatibility). The documentation is changed to only mention
the dash variants.
The commit also changes boolean options so that they can be prefixed
with 'no-' to negate their meaning. This will be relevant when we add
boolean options that default to `true` (as the planned
--diff-array-value for instance) and we want to provide a way to turn
the option off.

(PRE-93) Change CLI options to use dash instead of underscore

---

lib/puppet/application/preview.rb
lib/puppet_x/puppetlabs/migration/catalog_delta_model.rb
lib/puppet_x/puppetlabs/preview/api/documentation/preview-help.md
lib/puppet_x/puppetlabs/preview/api/schemas/catalog-delta.json
spec/unit/catalog_delta_model_spec.rb

This PR adds a new command line option `diff-array-value` which defaults to `true` (to retain backward compatibility) but can be turned off by using `--no-diff-array-value`. When it is turned off, a value in the baseline catalog will be considered equal to a one element array containing that value in the preview catalog.
The option can only be used together with `--migrate 3.8/4.0`.

(PRE-91) Add flag to suppress value vs [value] conflicts

---

README.md

This removes the banner in the README saying the module is PE-only.
It also adds detail of the equivalent open-source Puppet versions to the required PE versions.

(PRE-88) Update README for opensource release

---

spec/spec_helper_integration.rb

Ubuntu puppetdb termini string requires a version number with
-1puppetlabs1 on the end, only in the non-latest case.
This change should fix CI.

(maint) new puppetdb termini version string 4x

---

lib/puppet/application/preview.rb
lib/puppet/indirector/catalog/diff_compiler.rb
spec/unit/preview_spec.rb

Prior to this commit, a node that didn't have a valid factset would be
compiled anyway and cause a lot of errors. This made the output hard
to read. This commit ensures that the compilation of such nodes fails
with immediately with a single error indicating that facts seems to
be missing.

(PRE-100) Fail compilation of nodes that doesn't have a valid factset

---

spec/spec_helper_integration.rb

Previously, the acceptance test setup steps prevented re-running the
tests on provisioned hosts.  This change ensures idempotency in that
section of the setup, so one can run test(s) against previously
provisioned and installed hosts.
[skip ci]

(maint) preserved hosts mode

---

README.md
lib/puppet/application/preview.rb
lib/puppet_x/puppetlabs/migration/overview_model/report.rb
lib/puppet_x/puppetlabs/preview/api/documentation/preview-help.md
spec/unit/overview_report_spec.rb

This commit adds the flag --[no-]report-all. If true, the human
readable overview report (obtained with --view overview) will include
a list of all nodes, as opposed to a list limited to the top ten nodes
with most issues.
The default setting for the flag is `false`, i.e. only the top ten nodes
will be reported.

(PRE-101) Add flag to control node list output

---

README.md
lib/puppet/application/preview.rb
lib/puppet_x/puppetlabs/preview/api/documentation/preview-help.md

Prior to this commit, a compile was attempted for all nodes given on
the command line. Now, a check is instead made to see if the 'status'
action exists on the 'node' face. This action is provided by PuppetDB
and if it exists, it is used to obtain the status for each of the nodes.
Nodes that are found inactive will not be compiled unless the new option
--no-skip-inactive-nodes is given. Nodes that are not found at all will
not be compiled and result in an error printout. The preview command
will then continue with the next node.

(PRE-95) Add flag to skip/not skip nodes that are inactive

---

lib/puppet_x/puppetlabs/migration/overview_model/report.rb
spec/integration/preview_spec.rb
spec/unit/overview_report_spec.rb

Before this commit, issues reported under 'compilation_errors' and
issue locations reported under 'error_count_by_issue_code' and
'warning_count_by_issue_code' were duplicated <n> times where <n>
stands for the number of nodes that had the error/warning. This
commit ensures that such duplicates are eliminated.

(PRE-105) Ensure that issues and issue locations are reported uniquely

---

lib/puppet_x/puppetlabs/migration/overview_model/report.rb
spec/unit/overview_report_spec.rb

This commit replaces the simple "issue count" in the node list
with five counters for errors, warnings, added resources, removed
resources, and changed resources. It also changes the sorting of the
list to a descending sort based on errors, warnings, and the sum
of all resource counters.
The output produced by `--view overview` now outputs a table with node
name and counters for errors, warnings, and the sum of all resource
counters instead of just the node name and an issue counter.

(PRE-103) Improve sorting and information in "all nodes" list.

---

spec/integration/preview_spec.rb
spec/spec_helper_integration.rb

(PRE-106) remove node names not in puppetdb from tests
(PRE-106) add nodes to puppetdb for compilation
* catalog-preview now looks up nodes in puppetdb to determine if they are active or should be skipped
* "register" node names used in tests with puppetdb by adding facts for them

(PRE-106) test harness for catalog preview acceptance tests is broken

---

lib/puppet_x/puppetlabs/migration/overview_model/report.rb
spec/unit/overview_report_spec.rb
spec/unit/preview_spec.rb

Before this commit, the order of reported nodes was undefined if
the nodes had the same number of errors, warnings, and diffs. This
commit adds the node name the set ordering (with lowest prio).

(PRE-107) Ensure that the order is consistent when reporting nodes

---

lib/puppet/indirector/catalog/diff_compiler.rb
spec/unit/preview_spec.rb

The code assumed that the compile call would accept a block. That is
only true when using the call on a compiler instance, not on the class.
The subsequent test only "worked" on 4.x (since it was disabled there).
This commit ensures that the check for empty factset is in the correct
place and that the test works when using Puppet 3.8.x

(PRE-100) Fix failing test for 'No osfamily fact found'

---

spec/spec_helper_integration.rb

Recent changes require a populated osfamily fact for the tests to pass.
closes #149 
[skip ci]

(PRE-110) add osfamily staged fact for tests

---

lib/puppet/indirector/catalog/diff_compiler.rb
spec/integration/preview_spec.rb
spec/spec_helper_integration.rb
spec/unit/preview_spec.rb

This commit ensures that:
1. The curl command for updating PuppetDB is tailored to the PuppetDB
version that is currently in use.
2. The added facts are added to the environments 'production' and 'test'
for all nodes.
3. That tests that run in a non-root environment are pending (needs
proper configuration to access puppetdb).
4. That the error message for the missing 'osfamily' fact contains the
correct node name.

(PRE-110) Fix failing acceptance tests

---

README.md
lib/puppet_x/puppetlabs/preview/api/documentation/preview-help.md

The `--no-skip-inactive-nodes` flag is not yet functional and the
`--skip-inactive-nodes` behavior will be the default. So, the switch
currently does not change the behavior of catalog preview.
This commit removes the documentation for the switch from the README
and the `help` output. This documentation can be reinstated when the
`--no-skip-inactive-nodes` flag works.

(PRE-95) remove skip-inactive-nodes docs

---

spec/integration/preview_spec.rb

This commit updates the `skip-inactive-nodes` acceptance tests.
Some of the tests were attempting to use the `--view baseline` flag
when providing a node file with multiple nodes. This has been changed
to use the `--view none` flag.
The `puppetdb-version` was not being set in this test block to
make sure that the properly configured API was being used. This value
is now being set based on the `puppet-version`.
The set up steps in the context did not seem to execute consistently
prior to the individual tests. These have been wrapped in an rspec
`before(:all)` block to ensure that the setup steps are completed
before the tests commence.

(PRE-104) Fix acceptance baseline

---

spec/integration/preview_spec.rb

This commit sets the tests associated with the `--skip-inactive-nodes`
tests to pending. Currently, these tests fail due facts being attempted
to be retrieved for inactive nodes. See PRE-122.

(PRE-104) Set skip-inactive-nodes tests pending

---

lib/puppet/application/preview.rb
spec/integration/preview_spec.rb

This commit ensures that the method Preview#using_puppetdb? continues
to return `true` for the duration of a run. This was not the case
earlier since that method tested for the name of the Facts terminus and
when it was found to be 'puppetdb', that termnus was replaced with
the tailored 'diff_puppetdb' terminus. Subsequent calls to
#using_puppetdb? would hence return false. That in turn, broke the
test for if a node was active or deactivated.

(PRE-122) Inactive nodes not skipped by default

---

spec/integration/preview_spec.rb
spec/spec_helper_integration.rb

running catalog-preview as non-root requires some additional puppet and
puppetdb configuration.
* ensure the facts_terminus
* ensure we don't try to run as a ca, since preview runs in master mode
* ensure we have a unique certname to use as non-root
[skip ci]

(PRE-113) acceptance: configure non-root puppetdb

---

spec/integration/preview_spec.rb

test case https://github.com/puppetlabs/puppetlabs-catalog_preview/blob/master/spec/integration/preview_spec.rb#L605-L609 does not have --skip-inactive-nodes flag.
This PR adds the flag to the test case

(PRE-122) added --skip-inactive-nodes tag to a test

---

spec/spec_helper_integration.rb

no previewser group in sles..  but `chown` not really needed anyway.
[skip ci]

(PRE-113) acceptance: fix sles previewser group issue

---

lib/puppet_x/puppetlabs/migration/catalog_delta_model.rb
lib/puppet_x/puppetlabs/migration/overview_model.rb

require_relative was introduced in Ruby 1.9. Catalog-preview must run
with 1.8.7.

(PRE-123) Replace require_relative with require

---

Gemfile

This commit pins the dependency for rubocop to 0.41.2 if the ruby
version is less than 2.0.0 (definition copied from puppetlabs-stdlib).

(maint) Make tests run with Ruby 1.9.3

---

Gemfile

safe_yaml needs to be installed when testing puppet 4.6.1 with Ruby >= 2.3.0

(PRE-125) fix ci failure

---

spec/integration/nodesets/debian8-64mda.yaml

Apparently we are only setting the install-type in the nodeset files
because of the way beaker rspec runs.  Add the type so we don't try to
install PE when we don't want to.
[skip ci]

(PRE-124) fix debian8 nodeset file

---

Gemfile

* beaker-rspec pulls in beaker, no need to require it
[skip ci]

(PRE-124) use beaker-rpsec 6 required after pe gpg key change

---

README.md

This commit simply adds an example of a JSON file that the `--excludes` option will accept.  Some users are not familiar enough with JSON schemas to craft one simply from the output of `--schema excludes`.  This removes a potential barrier to using the catalog_preview module successfully.

Provide example of --excludes JSON file

---

.travis.yml
Gemfile

These gems are requirements for CI.Next. CI changes will follow
in ci-job-configs 
(maint) resolve bundled dependencies based upon RUBY_VERSION
* attempt to use `ruby RUBY_VERSION` in the Gemfile to resolve
transitive deps for us.  This only gets us so far. Some Gems do not
have `require_ruby_version` defined in their gemspec nor Gemfile, so
this method falls over at a certain point.
* we pin the other gems where required.
* we also attempt to pin beaker(-rspec) versions based upon required
transitive deps so we'll have to pin fewer of those in the future.
don't hold your breath.
* the beatings will continue until morale improves (until we can stop
testing against ruby 1.8.7)
(maint) allow ruby 1.8.7 in Gemfile
* Dir.home does not exist in ruby 1.8.7.  this should be os agnostic
* remove …

(QENG-4946) Add beaker-hostgen and beaker-abs to Gemfile

---

README.md

catalog_preview needs the ca option explicitly set to false in
order to work on a compile master. This was not documented
anywhere.

(PRE-128) Add documentation for compile master compatibility

---

Gemfile

Prior to this commit the listen gem (which the listen-guard gem
depends on) was not pinned to a particular version. Since the
latest version of the gem requires a Ruby version greater than 2.2
it was causing unit tests to fail on older versions.
Pin the listen gem to an older version so we can run with older
Ruby versions.

(maint) Pin listen gem version to prevent CI failures
